<img src='imgs/kaggle.png' align='left' />

# data = Kaggle IEEE fraud
## binary classification (is fraud)

<br/>
<br/>
<br/>
<br/>

# Setup

In [1]:
import pandas as pd

KAGGLE_PROJECT = 'ieee-fraud-detection'

SET_1 = 'transaction'
SET_2 = 'identity'

IDX_COL = 'TransactionID'

# Download Data

In [4]:
# !kaggle competitions download -c {KAGGLE_PROJECT} --force

In [5]:
# !unzip {KAGGLE_PROJECT}.zip

### csv -> pd

In [7]:
%%time
# 17 seconds

train_1 = pd.read_csv('train_' + SET_1 + '.csv', index_col=IDX_COL, low_memory=True)
train_1.sample(3)

CPU times: user 13.6 s, sys: 1.68 s, total: 15.2 s
Wall time: 15.3 s

,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
TransactionID,,,,,,,,,,,,,,,,,,,,,
3107103,0,2339061,34.98,C,9633,296.0,185.0,visa,138.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3256405,0,6540304,117.00,W,7815,161.0,150.0,mastercard,117.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3282956,0,7319161,29.00,W,6530,206.0,150.0,mastercard,126.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
%%time
# ~ 15 secs

train_2 = pd.read_csv('train_' + SET_2 + '.csv', index_col=IDX_COL, low_memory=True)
train_2.sample(3)

CPU times: user 458 ms, sys: 49.6 ms, total: 507 ms
Wall time: 507 ms

,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,id_10,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
TransactionID,,,,,,,,,,,,,,,,,,,,,
3102354,0.0,69839.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,android webview 4.0,32.0,NaN,match_status:2,T,F,T,T,mobile,SM-N950U Build/NMF26X
3314056,-5.0,159310.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,...,chrome 64.0,NaN,NaN,NaN,F,F,T,F,desktop,NaN
3571978,-5.0,129859.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,chrome 67.0,NaN,NaN,NaN,F,F,T,F,desktop,Windows

In [9]:
%%time
# 15 seconds

test_1 = pd.read_csv('test_' + SET_1 + '.csv', index_col=IDX_COL, low_memory=True)
test_1.sample(3)

CPU times: user 12.7 s, sys: 1.55 s, total: 14.2 s
Wall time: 14.3 s

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
TransactionID,,,,,,,,,,,,,,,,,,,,,
3762584,21737863,226.0,W,17055,393.0,150.0,mastercard,117.0,debit,325.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4120787,33246204,50.0,H,2772,512.0,150.0,visa,226.0,debit,143.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4106569,32976542,25.0,H,11106,100.0,150.0,visa,226.0,credit,337.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
%%time
# 1 second

test_2 = pd.read_csv('test_' + SET_2 + '.csv', index_col=IDX_COL, low_memory=True)
test_2.sample(3)

CPU times: user 480 ms, sys: 55.8 ms, total: 536 ms
Wall time: 538 ms

,id-01,id-02,id-03,id-04,id-05,id-06,id-07,id-08,id-09,id-10,...,id-31,id-32,id-33,id-34,id-35,id-36,id-37,id-38,DeviceType,DeviceInfo
TransactionID,,,,,,,,,,,,,,,,,,,,,
4015705,-5.0,269722.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,chrome 70.0,NaN,NaN,NaN,F,F,T,F,desktop,Windows
3952344,-5.0,43674.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,...,chrome 69.0,24.0,2736x1824,match_status:2,T,F,T,F,desktop,Windows
3700566,-5.0,4622.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,chrome 67.0,24.0,1920x1080,match_status:2,T,F,T,T,desktop,Windows

### merge / join / concatenate

In [11]:
train = train_1.merge(train_2, how='left', left_index=True, right_index=True)
del train_1, train_2

In [12]:
test = test_1.merge(test_2, how='left', left_index=True, right_index=True)
del test_1, test_2
test.columns = test.columns.str.replace("-", "_")

In [13]:
import numpy as np
test.insert(0, 'isFraud', np.repeat(-1,test.shape[0]))
del np

In [14]:
len(test.columns) == len(train.columns)

True

In [15]:
test_cols = list(test.columns)
test_cols.sort()

['C1',
 'C10',
 'C11',
 'C12',
 'C13',
 'C14',
 'C2',
 'C3',
 'C4',
 'C5',
 'C6',
 'C7',
 'C8',
 'C9',
 'D1',
 'D10',
 'D11',
 'D12',
 'D13',
 'D14',
 'D15',
 'D2',
 'D3',
 'D4',
 'D5',
 'D6',
 'D7',
 'D8',
 'D9',
 'DeviceInfo',
 'DeviceType',
 'M1',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'M7',
 'M8',
 'M9',
 'P_emaildomain',
 'ProductCD',
 'R_emaildomain',
 'TransactionAmt',
 'TransactionDT',
 'V1',
 'V10',
 'V100',
 'V101',
 'V102',
 'V103',
 'V104',
 'V105',
 'V106',
 'V107',
 'V108',
 'V109',
 'V11',
 'V110',
 'V111',
 'V112',
 'V113',
 'V114',
 'V115',
 'V116',
 'V117',
 'V118',
 'V119',
 'V12',
 'V120',
 'V121',
 'V122',
 'V123',
 'V124',
 'V125',
 'V126',
 'V127',
 'V128',
 'V129',
 'V13',
 'V130',
 'V131',
 'V132',
 'V133',
 'V134',
 'V135',
 'V136',
 'V137',
 'V138',
 'V139',
 'V14',
 'V140',
 'V141',
 'V142',
 'V143',
 'V144',
 'V145',
 'V146',
 'V147',
 'V148',
 'V149',
 'V15',
 'V150',
 'V151',
 'V152',
 'V153',
 'V154',
 'V155',
 'V156',
 'V157',
 'V158',
 'V159',
 'V16',
 'V160',
 'V161',
 'V162',
 'V163',
 'V164',
 'V165',
 'V166',
 'V167',
 'V168',
 'V169',
 'V17',
 'V170',
 'V171',
 'V172',
 'V173',
 'V174',
 'V175',
 'V176',
 'V177',
 'V178',
 'V179',
 'V18',
 'V180',
 'V181',
 'V182',
 'V183',
 'V184',
 'V185',
 'V186',
 'V187',
 'V188',
 'V189',
 'V19',
 'V190',
 'V191',
 'V192',
 'V193',
 'V194',
 'V195',
 'V196',
 'V197',
 'V198',
 'V199',
 'V2',
 'V20',
 'V200',
 'V201',
 'V202',
 'V203',
 'V204',
 'V205',
 'V206',
 'V207',
 'V208',
 'V209',
 'V21',
 'V210',
 'V211',
 'V212',
 'V213',
 'V214',
 'V215',
 'V216',
 'V217',
 'V218',
 'V219',
 'V22',
 'V220',
 'V221',
 'V222',
 'V223',
 'V224',
 'V225',
 'V226',
 'V227',
 'V228',
 'V229',
 'V23',
 'V230',
 'V231',
 'V232',
 'V233',
 'V234',
 'V235',
 'V236',
 'V237',
 'V238',
 'V239',
 'V24',
 'V240',
 'V241',
 'V242',
 'V243',
 'V244',
 'V245',
 'V246',
 'V247',
 'V248',
 'V249',
 'V25',
 'V250',
 'V251',
 'V252',
 'V253',
 'V254',
 'V255',
 'V256',
 'V257',
 'V258',
 'V259',
 'V26',
 'V260',
 'V261',
 'V262',
 'V263',
 'V264',
 'V265',
 'V266',
 'V267',
 'V268',
 'V269',
 'V27',
 'V270',
 'V271',
 'V272',
 'V273',
 'V274',
 'V275',
 'V276',
 'V277',
 'V278',
 'V279',
 'V28',
 'V280',
 'V281',
 'V282',
 'V283',
 'V284',
 'V285',
 'V286',
 'V287',
 'V288',
 'V289',
 'V29',
 'V290',
 'V291',
 'V292',
 'V293',
 'V294',
 'V295',
 'V296',
 'V297',
 'V298',
 'V299',
 'V3',
 'V30',
 'V300',
 'V301',
 'V302',
 'V303',
 'V304',
 'V305',
 'V306',
 'V307',
 'V308',
 'V309',
 'V31',
 'V310',
 'V311',
 'V312',
 'V313',
 'V314',
 'V315',
 'V316',
 'V317',
 'V318',
 'V319',
 'V32',
 'V320',
 'V321',
 'V322',
 'V323',
 'V324',
 'V325',
 'V326',
 'V327',
 'V328',
 'V329',
 'V33',
 'V330',
 'V331',
 'V332',
 'V333',
 'V334',
 'V335',
 'V336',
 'V337',
 'V338',
 'V339',
 'V34',
 'V35',
 'V36',
 'V37',
 'V38',
 'V39',
 'V4',
 'V40',
 'V41',
 'V42',
 'V43',
 'V44',
 'V45',
 'V46',
 'V47',
 'V48',
 'V49',
 'V5',
 'V50',
 'V51',
 'V52',
 'V53',
 'V54',
 'V55',
 'V56',
 'V57',
 'V58',
 'V59',
 'V6',
 'V60',
 'V61',
 'V62',
 'V63',
 'V64',
 'V65',
 'V66',
 'V67',
 'V68',
 'V69',
 'V7',
 'V70',
 'V71',
 'V72',
 'V73',
 'V74',
 'V75',
 'V76',
 'V77',
 'V78',
 'V79',
 'V8',
 'V80',
 'V81',
 'V82',
 'V83',
 'V84',
 'V85',
 'V86',
 'V87',
 'V88',
 'V89',
 'V9',
 'V90',
 'V91',
 'V92',
 'V93',
 'V94',
 'V95',
 'V96',
 'V97',
 'V98',
 'V99',
 'addr1',
 'addr2',
 'card1',
 'card2',
 'card3',
 'card4',
 'card5',
 'card6',
 'dist1',
 'dist2',
 'id_01',
 'id_02',
 'id_03',
 'id_04',
 'id_05',
 'id_06',
 'id_07',
 'id_08',
 'id_09',
 'id_10',
 'id_11',
 'id_12',
 'id_13',
 'id_14',
 'id_15',
 'id_16',
 'id_17',
 'id_18',
 'id_19',
 'id_20',
 'id_21',
 'id_22',
 'id_23',
 'id_24',
 'id_25',
 'id_26',
 'id_27',
 'id_28',
 'id_29',
 'id_30',
 'id_31',
 'id_32',
 'id_33',
 'id_34',
 'id_35',
 'id_36',
 'id_37',
 'id_38',
 'isFraud']

In [16]:
train_cols = list(train.columns)
train_cols.sort()

['C1',
 'C10',
 'C11',
 'C12',
 'C13',
 'C14',
 'C2',
 'C3',
 'C4',
 'C5',
 'C6',
 'C7',
 'C8',
 'C9',
 'D1',
 'D10',
 'D11',
 'D12',
 'D13',
 'D14',
 'D15',
 'D2',
 'D3',
 'D4',
 'D5',
 'D6',
 'D7',
 'D8',
 'D9',
 'DeviceInfo',
 'DeviceType',
 'M1',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'M7',
 'M8',
 'M9',
 'P_emaildomain',
 'ProductCD',
 'R_emaildomain',
 'TransactionAmt',
 'TransactionDT',
 'V1',
 'V10',
 'V100',
 'V101',
 'V102',
 'V103',
 'V104',
 'V105',
 'V106',
 'V107',
 'V108',
 'V109',
 'V11',
 'V110',
 'V111',
 'V112',
 'V113',
 'V114',
 'V115',
 'V116',
 'V117',
 'V118',
 'V119',
 'V12',
 'V120',
 'V121',
 'V122',
 'V123',
 'V124',
 'V125',
 'V126',
 'V127',
 'V128',
 'V129',
 'V13',
 'V130',
 'V131',
 'V132',
 'V133',
 'V134',
 'V135',
 'V136',
 'V137',
 'V138',
 'V139',
 'V14',
 'V140',
 'V141',
 'V142',
 'V143',
 'V144',
 'V145',
 'V146',
 'V147',
 'V148',
 'V149',
 'V15',
 'V150',
 'V151',
 'V152',
 'V153',
 'V154',
 'V155',
 'V156',
 'V157',
 'V158',
 'V159',
 'V16',
 'V160',
 'V161',
 'V162',
 'V163',
 'V164',
 'V165',
 'V166',
 'V167',
 'V168',
 'V169',
 'V17',
 'V170',
 'V171',
 'V172',
 'V173',
 'V174',
 'V175',
 'V176',
 'V177',
 'V178',
 'V179',
 'V18',
 'V180',
 'V181',
 'V182',
 'V183',
 'V184',
 'V185',
 'V186',
 'V187',
 'V188',
 'V189',
 'V19',
 'V190',
 'V191',
 'V192',
 'V193',
 'V194',
 'V195',
 'V196',
 'V197',
 'V198',
 'V199',
 'V2',
 'V20',
 'V200',
 'V201',
 'V202',
 'V203',
 'V204',
 'V205',
 'V206',
 'V207',
 'V208',
 'V209',
 'V21',
 'V210',
 'V211',
 'V212',
 'V213',
 'V214',
 'V215',
 'V216',
 'V217',
 'V218',
 'V219',
 'V22',
 'V220',
 'V221',
 'V222',
 'V223',
 'V224',
 'V225',
 'V226',
 'V227',
 'V228',
 'V229',
 'V23',
 'V230',
 'V231',
 'V232',
 'V233',
 'V234',
 'V235',
 'V236',
 'V237',
 'V238',
 'V239',
 'V24',
 'V240',
 'V241',
 'V242',
 'V243',
 'V244',
 'V245',
 'V246',
 'V247',
 'V248',
 'V249',
 'V25',
 'V250',
 'V251',
 'V252',
 'V253',
 'V254',
 'V255',
 'V256',
 'V257',
 'V258',
 'V259',
 'V26',
 'V260',
 'V261',
 'V262',
 'V263',
 'V264',
 'V265',
 'V266',
 'V267',
 'V268',
 'V269',
 'V27',
 'V270',
 'V271',
 'V272',
 'V273',
 'V274',
 'V275',
 'V276',
 'V277',
 'V278',
 'V279',
 'V28',
 'V280',
 'V281',
 'V282',
 'V283',
 'V284',
 'V285',
 'V286',
 'V287',
 'V288',
 'V289',
 'V29',
 'V290',
 'V291',
 'V292',
 'V293',
 'V294',
 'V295',
 'V296',
 'V297',
 'V298',
 'V299',
 'V3',
 'V30',
 'V300',
 'V301',
 'V302',
 'V303',
 'V304',
 'V305',
 'V306',
 'V307',
 'V308',
 'V309',
 'V31',
 'V310',
 'V311',
 'V312',
 'V313',
 'V314',
 'V315',
 'V316',
 'V317',
 'V318',
 'V319',
 'V32',
 'V320',
 'V321',
 'V322',
 'V323',
 'V324',
 'V325',
 'V326',
 'V327',
 'V328',
 'V329',
 'V33',
 'V330',
 'V331',
 'V332',
 'V333',
 'V334',
 'V335',
 'V336',
 'V337',
 'V338',
 'V339',
 'V34',
 'V35',
 'V36',
 'V37',
 'V38',
 'V39',
 'V4',
 'V40',
 'V41',
 'V42',
 'V43',
 'V44',
 'V45',
 'V46',
 'V47',
 'V48',
 'V49',
 'V5',
 'V50',
 'V51',
 'V52',
 'V53',
 'V54',
 'V55',
 'V56',
 'V57',
 'V58',
 'V59',
 'V6',
 'V60',
 'V61',
 'V62',
 'V63',
 'V64',
 'V65',
 'V66',
 'V67',
 'V68',
 'V69',
 'V7',
 'V70',
 'V71',
 'V72',
 'V73',
 'V74',
 'V75',
 'V76',
 'V77',
 'V78',
 'V79',
 'V8',
 'V80',
 'V81',
 'V82',
 'V83',
 'V84',
 'V85',
 'V86',
 'V87',
 'V88',
 'V89',
 'V9',
 'V90',
 'V91',
 'V92',
 'V93',
 'V94',
 'V95',
 'V96',
 'V97',
 'V98',
 'V99',
 'addr1',
 'addr2',
 'card1',
 'card2',
 'card3',
 'card4',
 'card5',
 'card6',
 'dist1',
 'dist2',
 'id_01',
 'id_02',
 'id_03',
 'id_04',
 'id_05',
 'id_06',
 'id_07',
 'id_08',
 'id_09',
 'id_10',
 'id_11',
 'id_12',
 'id_13',
 'id_14',
 'id_15',
 'id_16',
 'id_17',
 'id_18',
 'id_19',
 'id_20',
 'id_21',
 'id_22',
 'id_23',
 'id_24',
 'id_25',
 'id_26',
 'id_27',
 'id_28',
 'id_29',
 'id_30',
 'id_31',
 'id_32',
 'id_33',
 'id_34',
 'id_35',
 'id_36',
 'id_37',
 'id_38',
 'isFraud']

In [17]:
diff = (list(set(train_cols) - set(test_cols)))
diff.sort()
diff

[]

In [26]:
from pandas.util.testing import assert_frame_equal
try:
    assert_frame_equal(train, test)
except AssertionError as ae:    
    print(ae)
del assert_frame_equal

DataFrame are different

DataFrame shape mismatch
[left]:  (590540, 433)
[right]: (506691, 433)

In [19]:
test.columns[test.columns != train.columns]

Index([], dtype='object')

In [20]:
train.columns[test.columns != train.columns]

Index([], dtype='object')

In [22]:
%%time
# 10 seconds

df = pd.concat([train, test])

CPU times: user 3.16 s, sys: 3.99 s, total: 7.16 s
Wall time: 7.92 s

In [ ]:
del pd, IDX_COL, KAGGLE_PROJECT, SET_1, SET_2, test, test_cols, train, train_cols, diff

In [33]:
%whos

Variable   Type         Data/Info
---------------------------------
df         DataFrame                   isFraud  T<...>97231 rows x 433 columns]

# check types

### fn -- check for non-nums

In [53]:
# print n unique vals for non-num cols
def col_types(df, encode_limit=5):
    import numpy as np
    import pandas as pd
    
    cat_cols = []
    
    for c in df.columns:

        #if not np.issubdtype(df[c].dtype, np.number):        
        
        cat_col_info = {}
        cat_col_info['name'] = c
        cat_col_info['n_unique'] = df[c].nunique()
        cat_col_info['encodable'] = df[c].nunique() <= encode_limit
        cat_col_info['binary'] = df[c].nunique() == 2 
        cat_col_info['dtype'] = df[c].dtype

        cat_cols.append(cat_col_info)

    return pd.DataFrame.from_dict(cat_cols)

In [ ]:
def convert_binary(df, col):
    import numpy as np
    for c in df.columns:
        if not np.issubdtype(df[c].dtype, np.number):

            print(c , ' NOT num...', df[c].nunique())
            if (df[c].nunique() == 2):

In [56]:
col_meta = col_types(df)

In [66]:
display(col_meta[col_meta['n_unique'] < 3].sort_values(by='n_unique'))
col_meta[(col_meta['n_unique'] > 3) & (col_meta['n_unique'] < 10)].sort_values(by='n_unique')

          name  n_unique  encodable  binary    dtype
426      id_34         4       True   False   object
7        card4         4       True   False   object
9        card6         4       True   False   object
172       V119         4       True   False  float64
171       V118         4       True   False  float64
170       V117         4       True   False  float64
175       V122         5       True   False  float64
174       V121         5       True   False  float64
173       V120         5       True   False  float64
88         V35         5       True   False  float64
3    ProductCD         5       True   False   object
65         V12         5       True   False  float64
82         V29         6      False   False  float64
294       V241         6      False   False  float64
128        V75         6      False   False  float64
143        V90         6      False   False  float64
424      id_32         6      False   False  float64
101        V48         6      False   False  float64
63         V10         6      False   False  float64
122        V69         6      False   False  float64
106        V53         6      False   False  float64
74         V21         6      False   False  float64
124        V71         7      False   False  float64
114        V61         7      False   False  float64
66         V13         7      False   False  float64
194       V141         7      False   False  float64
89         V36         7      False   False  float64
293       V240         7      False   False  float64
110        V57         7      False   False  float64
142        V89         8      False   False  float64
146        V93         8      False   False  float64
145        V92         8      False   False  float64
64         V11         8      False   False  float64
247       V194         8      False   False  float64
136        V83         8      False   False  float64
132        V79         8      False   False  float64
81         V28         8      False   False  float64
80         V27         8      False   False  float64
102        V49         8      False   False  float64
103        V50         8      False   False  float64
135        V82         8      False   False  float64
107        V54         8      False   False  float64
129        V76         8      False   False  float64
121        V68         8      False   False  float64
161       V108         9      False   False  float64
339       V286         9      False   False  float64
83         V30         9      False   False  float64
95         V42         9      False   False  float64
227       V174         9      False   False  float64
99         V46         9      False   False  float64
126        V73         9      False   False  float64
144        V91         9      False   False  float64
104        V51         9      False   False  float64
116        V63         9      False   False  float64
75         V22         9      False   False  float64
163       V110         9      False   False  float64
162       V109         9      False   False  float64
119        V66         9      False   False  float64
123        V70         9      False   False  float64

In [70]:
df.V70.unique()

array([ 0., nan,  1.,  2.,  4.,  5.,  3.,  6.,  7.,  8.])

In [72]:
%%time
#


min_df = reduce_mem_usage(df)

isFraud
TransactionDT
TransactionAmt
ProductCD
card1
card2
card3
card4
card5
card6
addr1
addr2
dist1
dist2
P_emaildomain
R_emaildomain
C1
C2
C3
C4
C5
C6
C7
C8
C9
C10
C11
C12
C13
C14
D1
D2
D3
D4
D5
D6
D7
D8
D9
D10
D11
D12
D13
D14
D15
M1
M2
M3
M4
M5
M6
M7
M8
M9
V1
V2
V3
V4
V5
V6
V7
V8
V9
V10
V11
V12
V13
V14
V15
V16
V17
V18
V19
V20
V21
V22
V23
V24
V25
V26
V27
V28
V29
V30
V31
V32
V33
V34
V35
V36
V37
V38
V39
V40
V41
V42
V43
V44
V45
V46
V47
V48
V49
V50
V51
V52
V53
V54
V55
V56
V57
V58
V59
V60
V61
V62
V63
V64
V65
V66
V67
V68
V69
V70
V71
V72
V73
V74
V75
V76
V77
V78
V79
V80
V81
V82
V83
V84
V85
V86
V87
V88
V89
V90
V91
V92
V93
V94
V95
V96
V97
V98
V99
V100
V101
V102
V103
V104
V105
V106
V107
V108
V109
V110
V111
V112
V113
V114
V115
V116
V117
V118
V119
V120
V121
V122
V123
V124
V125
V126
V127
V128
V129
V130
V131
V132
V133
V134
V135
V136
V137
V138
V139
V140
V141
V142
V143
V144
V145
V146
V147
V148
V149
V150
V151
V152
V153
V154
V155
V156
V157
V158
V159
V160
V161
V162
V163
V164
V165
V166
V167
V168
V169
V170
V171
V172
V173
V174
V175
V176
V177
V178
V179
V180
V181
V182
V183
V184
V185
V186
V187
V188
V189
V190
V191
V192
V193
V194
V195
V196
V197
V198
V199
V200
V201
V202
V203
V204
V205
V206
V207
V208
V209
V210
V211
V212
V213
V214
V215
V216
V217
V218
V219
V220
V221
V222
V223
V224
V225
V226
V227
V228
V229
V230
V231
V232
V233
V234
V235
V236
V237
V238
V239
V240
V241
V242
V243
V244
V245
V246
V247
V248
V249
V250
V251
V252
V253
V254
V255
V256
V257
V258
V259
V260
V261
V262
V263
V264
V265
V266
V267
V268
V269
V270
V271
V272
V273
V274
V275
V276
V277
V278
V279
V280
V281
V282
V283
V284
V285
V286
V287
V288
V289
V290
V291
V292
V293
V294
V295
V296
V297
V298
V299
V300
V301
V302
V303
V304
V305
V306
V307
V308
V309
V310
V311
V312
V313
V314
V315
V316
V317
V318
V319
V320
V321
V322
V323
V324
V325
V326
V327
V328
V329
V330
V331
V332
V333
V334
V335
V336
V337
V338
V339
id_01
id_02
id_03
id_04
id_05
id_06
id_07
id_08
id_09
id_10
id_11
id_12
id_13
id_14
id_15
id_16
id_17
id_18
id_19
id_20
id_21
id_22
id_23
id_24
id_25
id_26
id_27
id_28
id_29
id_30
id_31
id_32
id_33
id_34
id_35
id_36
id_37
id_38
DeviceType
DeviceInfo
calculating memory usage...
Mem. usage decreased to 1221.15 Mb (66.4% reduction)

### booleans (T/F) -> integers

In [6]:
for i in range(1,10):
    df['M' + str(i)] = df['M' + str(i)].eq('T').mul(1)

### remove cols w/ large n unique vals

In [7]:
df = df.drop(columns=['P_emaildomain', 'R_emaildomain'], axis=1)

# ENCODING

### FREQUENCY ENCODE

In [ ]:
def encode_FE(df, cols):
    for col in cols:
        vc = df.value_counts(dropna=True, normalize=True).to_dict()
        vc[-1] = -1
        nm = col+'_FE'
        df1[nm] = df1[col].map(vc)
        df1[nm] = df1[nm].astype('float32')
        df2[nm] = df2[col].map(vc)
        df2[nm] = df2[nm].astype('float32')
        print(nm,', ',end='')

### LABEL ENCODE

In [ ]:
def encode_LE(col,train=X_train,test=X_test,verbose=True):
    df_comb = pd.concat([train[col],test[col]],axis=0)
    df_comb,_ = df_comb.factorize(sort=True)
    nm = col
    if df_comb.max()>32000: 
        train[nm] = df_comb[:len(train)].astype('int32')
        test[nm] = df_comb[len(train):].astype('int32')
    else:
        train[nm] = df_comb[:len(train)].astype('int16')
        test[nm] = df_comb[len(train):].astype('int16')
    del df_comb; x=gc.collect()
    if verbose: print(nm,', ',end='')

### GROUP AGGREGATION MEAN AND STD
https://www.kaggle.com/kyakovlev/ieee-fe-with-some-eda

In [ ]:
def encode_AG(main_columns, uids, aggregations=['mean'], train_df=X_train, test_df=X_test, 
              fillna=True, usena=False):
    # AGGREGATION OF MAIN WITH UID FOR GIVEN STATISTICS
    for main_column in main_columns:  
        for col in uids:
            for agg_type in aggregations:
                new_col_name = main_column+'_'+col+'_'+agg_type
                temp_df = pd.concat([train_df[[col, main_column]], test_df[[col,main_column]]])
                if usena: temp_df.loc[temp_df[main_column]==-1,main_column] = np.nan
                temp_df = temp_df.groupby([col])[main_column].agg([agg_type]).reset_index().rename(
                                                        columns={agg_type: new_col_name})

                temp_df.index = list(temp_df[col])
                temp_df = temp_df[new_col_name].to_dict()   

                train_df[new_col_name] = train_df[col].map(temp_df).astype('float32')
                test_df[new_col_name]  = test_df[col].map(temp_df).astype('float32')
                
                if fillna:
                    train_df[new_col_name].fillna(-1,inplace=True)
                    test_df[new_col_name].fillna(-1,inplace=True)
                
                print("'"+new_col_name+"'",', ',end='')

### COMBINE FEATURES

In [ ]:
def encode_CB(col1,col2,df1=X_train,df2=X_test):
    nm = col1+'_'+col2
    df1[nm] = df1[col1].astype(str)+'_'+df1[col2].astype(str)
    df2[nm] = df2[col1].astype(str)+'_'+df2[col2].astype(str) 
    encode_LE(nm,verbose=False)
    print(nm,', ',end='')

### GROUP AGGREGATION NUNIQUE

In [43]:
def encode_AG2(main_columns, uids, train_df=X_train, test_df=X_test):
    for main_column in main_columns:  
        for col in uids:
            comb = pd.concat([train_df[[col]+[main_column]],test_df[[col]+[main_column]]],axis=0)
            mp = comb.groupby(col)[main_column].agg(['nunique'])['nunique'].to_dict()
            train_df[col+'_'+main_column+'_ct'] = train_df[col].map(mp).astype('float32')
            test_df[col+'_'+main_column+'_ct'] = test_df[col].map(mp).astype('float32')
            print(col+'_'+main_column+'_ct, ',end='')

NameError: name 'X_train' is not defined

### one hot encode

In [8]:
df = pd.concat([df, pd.get_dummies(df['ProductCD'], drop_first=True)], axis=1)
df = df.drop(columns=['ProductCD'], axis=1)

In [9]:
df = pd.concat([df, pd.get_dummies(df['card4'])], axis=1)
df = df.drop(columns=['card4'], axis=1)

In [10]:
df = pd.concat([df, pd.get_dummies(df['card6'])], axis=1)
df = df.drop(columns=['card6'], axis=1)

### check types again

In [11]:
col_types(df)

### impute

In [12]:
# impute with mean value
for c in df.columns:
    df[c] = df[c].fillna(df[c].mean())

### minify

In [71]:
def minify(df, verbose=True):
    import numpy as np
    numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
    start_mem = df.memory_usage().sum() / 1024**2    
    for col in df.columns:
        if verbose:
            print(col)
        col_type = df[col].dtypes
        if col_type in numerics:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)    
    end_mem = df.memory_usage().sum() / 1024**2
    if verbose: 
        print('calculating memory usage...')
        print('Mem. usage decreased to {:5.2f} Mb ({:.1f}% reduction)'.format(end_mem, 100 * (start_mem - end_mem) / start_mem))
    return df

In [14]:
%%time
# 30 seconds
df = reduce_mem_usage(df)

TransactionID
isFraud
TransactionDT
TransactionAmt
card1
card2
card3
card5
addr1
addr2
dist1
dist2
C1
C2
C3
C4
C5
C6
C7
C8
C9
C10
C11
C12
C13
C14
D1
D2
D3
D4
D5
D6
D7
D8
D9
D10
D11
D12
D13
D14
D15
M1
M2
M3
M4
M5
M6
M7
M8
M9
V1
V2
V3
V4
V5
V6
V7
V8
V9
V10
V11
V12
V13
V14
V15
V16
V17
V18
V19
V20
V21
V22
V23
V24
V25
V26
V27
V28
V29
V30
V31
V32
V33
V34
V35
V36
V37
V38
V39
V40
V41
V42
V43
V44
V45
V46
V47
V48
V49
V50
V51
V52
V53
V54
V55
V56
V57
V58
V59
V60
V61
V62
V63
V64
V65
V66
V67
V68
V69
V70
V71
V72
V73
V74
V75
V76
V77
V78
V79
V80
V81
V82
V83
V84
V85
V86
V87
V88
V89
V90
V91
V92
V93
V94
V95
V96
V97
V98
V99
V100
V101
V102
V103
V104
V105
V106
V107
V108
V109
V110
V111
V112
V113
V114
V115
V116
V117
V118
V119
V120
V121
V122
V123
V124
V125
V126
V127
V128
V129
V130
V131
V132
V133
V134
V135
V136
V137
V138
V139
V140
V141
V142
V143
V144
V145
V146
V147
V148
V149
V150
V151
V152
V153
V154
V155
V156
V157
V158
V159
V160
V161
V162
V163
V164
V165
V166
V167
V168
V169
V170
V171
V172
V173
V174
V175
V176
V177
V178
V179
V180
V181
V182
V183
V184
V185
V186
V187
V188
V189
V190
V191
V192
V193
V194
V195
V196
V197
V198
V199
V200
V201
V202
V203
V204
V205
V206
V207
V208
V209
V210
V211
V212
V213
V214
V215
V216
V217
V218
V219
V220
V221
V222
V223
V224
V225
V226
V227
V228
V229
V230
V231
V232
V233
V234
V235
V236
V237
V238
V239
V240
V241
V242
V243
V244
V245
V246
V247
V248
V249
V250
V251
V252
V253
V254
V255
V256
V257
V258
V259
V260
V261
V262
V263
V264
V265
V266
V267
V268
V269
V270
V271
V272
V273
V274
V275
V276
V277
V278
V279
V280
V281
V282
V283
V284
V285
V286
V287
V288
V289
V290
V291
V292
V293
V294
V295
V296
V297
V298
V299
V300
V301
V302
V303
V304
V305
V306
V307
V308
V309
V310
V311
V312
V313
V314
V315
V316
V317
V318
V319
V320
V321
V322
V323
V324
V325
V326
V327
V328
V329
V330
V331
V332
V333
V334
V335
V336
V337
V338
V339
H
R
S
W
american express
discover
mastercard
visa
charge card
credit
debit
debit or credit
calculating memory usage...
Mem. usage decreased to 491.10 Mb (72.1% reduction)
CPU times: user 1min 54s, sys: 1min 31s, total: 3min 25s
Wall time: 3min 25s

### normalization

<img src='imgs/std_scale.png' />

In [15]:
# mean normalize
# df = (df-df.mean()) / df.std()

# min-max
# df = (df-df.min())/(df.max()-df.min())

### save

In [17]:
df.to_csvv('fraud_all.csv')

### shuffle, split, save

In [16]:
n_div_4 = int(df.shape[0] / 4)
n_div_4

147635

In [23]:
from sklearn.model_selection import train_test_split

splits = []

df, df_0   = train_test_split(df, test_size=n_div_4, random_state=0, shuffle=True)
splits.append(df_0)

df, df_1   = train_test_split(df, test_size=n_div_4, random_state=0, shuffle=True)
splits.append(df_1)

df_3, df_2 = train_test_split(df, test_size=n_div_4, random_state=0, shuffle=True)
splits.append(df_2)
splits.append(df_3)

In [24]:
# save memory
del df

### save splits

In [25]:
%%time

for i, split in enumerate(splits):
    print(i)
    split.to_csv('fraud_' + str(i) + '.csv')

0
1
2
3

In [6]:
!wc -l *.csv

   25001 fraud_0.csv
   25001 fraud_1.csv
   25001 fraud_2.csv
   25001 fraud_3.csv
  590541 fraud_all.csv
  590541 train_transaction.csv
 1281086 total

In [7]:
!du -h *.csv

 48M	fraud_0.csv
 48M	fraud_1.csv
 48M	fraud_2.csv
 48M	fraud_3.csv
1.1G	fraud_all.csv
655M	train_transaction.csv

In [8]:
!head -2 fraud_0.csv | tail -1

361644,3348644,0,8971373,200.0,6019,583.0,150.0,226.0,143.0,87.0,116.44,238.8,1.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,169.9,28.39,140.1,42.44,69.5,41.6,127.8,0.8335,124.1,146.8,54.62,18.22,59.1,163.5,0,0,0,0,0,0,0,0,0,1.0,1.044,1.076,0.8467,0.877,1.045,1.072,1.027,1.04,0.465,0.4792,0.5576,0.5967,0.9995,0.1226,0.1235,0.1353,0.1365,0.8164,0.8467,0.1306,0.1333,1.035,1.058,0.9775,0.9873,0.000723,0.000803,0.3892,0.4075,0.141,0.1425,0.1313,0.1396,0.5405,0.5776,1.106,1.159,0.1671,0.1785,0.9995,0.1566,0.1688,1.084,1.12,1.022,1.038,0.3845,0.3992,0.1649,0.1715,0.184,0.5757,0.617,1.067,1.119,0.1292,0.1332,0.1356,0.1439,0.8296,0.867,0.1316,0.1423,0.9995,0.9805,0.997,0.0005636,0.3906,0.4087,0.1416,0.146,0.1409,0.1528,0.542,0.5864,1.087,1.143,0.137,0.1454,0.1543,0.8447,0.8823,0.1382,0.1509,1.065,1.1,0.999,0.0009184,0.4036,0.4224,0.1509,0.1552,0.1375,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,200.0,1.0,1.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,200.0,200.0,200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,200.0,200.0,200.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,2.0,2.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,200.0,200.0,200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,200.0,200.0,200.0,1.0,1.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,200.0,200.0,200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,200.0,200.0,200.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,200.0,200.0,200.0,0.0,0.0,0.0,200.0,200.0,200.0,0,1,0,0,0,0,0,1,0,1,0,0

In [9]:
!head -2 fraud_1.csv | tail -1

45903,3032903,0,1103448,40.0,16075,514.0,150.0,102.0,330.0,87.0,116.44,15.0,6.0,2.0,0.0,1.0,0.0,0.0,0.0,3.0,0.0,4.0,1.0,0.0,7.0,3.0,0.0,169.9,28.39,140.1,42.44,69.5,41.6,519.0,0.75,124.1,146.8,54.62,18.22,257.0,163.5,0,0,0,0,0,0,0,0,0,1.0,1.044,1.076,0.8467,0.877,1.045,1.072,1.027,1.04,0.465,0.4792,0.5576,0.5967,0.9995,0.1226,0.1235,0.1353,0.1365,0.8164,0.8467,0.1306,0.1333,1.035,1.058,0.9775,0.9873,0.000723,0.000803,0.3892,0.4075,0.141,0.1425,0.1313,0.1396,0.5405,0.5776,1.106,1.159,0.1671,0.1785,0.9995,0.1566,0.1688,1.084,1.12,1.022,1.038,0.3845,0.3992,0.1649,0.1715,0.184,0.5757,0.617,1.067,1.119,0.1292,0.1332,0.1356,0.1439,0.8296,0.867,0.1316,0.1423,0.9995,0.9805,0.997,0.0005636,0.3906,0.4087,0.1416,0.146,0.1409,0.1528,0.542,0.5864,1.087,1.143,0.137,0.1454,0.1543,0.8447,0.8823,0.1382,0.1509,1.065,1.1,0.999,0.0009184,0.4036,0.4224,0.1509,0.1552,0.1375,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,40.0,40.0,40.0,0.0,0.0,0.0,40.0,40.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,3.0,3.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,160.0,160.0,120.0,7.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,4.0,4.0,4.0,3.0,3.0,3.0,3.0,0.0,0.0,1.0,1.0,0.0,0.0,2.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0,0.0,280.0,280.0,280.0,0.0,0.0,0.0,0.0,0.0,0.0,160.0,160.0,160.0,120.0,120.0,120.0,7.0,7.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,2.0,2.0,2.0,4.0,4.0,4.0,3.0,3.0,3.0,3.0,0.0,0.0,1.0,1.0,1.0,1.0,2.0,0.0,2.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,4.0,4.0,0.0,2.0,2.0,2.0,280.0,280.0,280.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,160.0,160.0,160.0,120.0,120.0,120.0,4.0,4.0,0.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,4.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,160.0,160.0,160.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,160.0,160.0,160.0,0.0,0.0,0.0,7.0,7.0,7.0,0.0,0.0,0.0,3.0,3.0,3.0,280.0,280.0,280.0,0.0,0.0,0.0,120.0,120.0,120.0,0,0,1,0,0,0,1,0,0,1,0,0